apiVersion: apps/v1
kind: Deployment
metadata:
  name: wdc-project-backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-wdc-project-backend
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2021-05-26T17:34:22Z"
        field.cattle.io/ports: '[[{"containerPort":3000,"dnsName":"wdc-project-backend","hostPort":0,"kind":"ClusterIP","name":"express","protocol":"TCP","sourcePort":3000}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-wdc-project-backend
    spec:
      containers:
      - image: akide/covid_contact_tracing_system_backend:918328473-83ec7f536d55431dd59415fdefb9fad1c1ffa080
        imagePullPolicy: Always
        name: wdc-project-backend
        ports:
        - containerPort: 3000
          name: express
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
